<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class GamificationBadgeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        $badges = [
            // Onboarding Badges
            [
                'name' => 'Primeira Etapa',
                'slug' => 'first-step',
                'description' => 'Completou o primeiro passo do cadastro',
                'icon_name' => 'flag',
                'icon_color' => '#10B981',
                'category' => 'onboarding',
                'rarity' => 'common',
                'points_value' => 10,
                'criteria' => json_encode(['onboarding_step' => 1]),
                'is_active' => true,
                'is_secret' => false,
                'sort_order' => 1,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Perfil Completo',
                'slug' => 'complete-profile',
                'description' => 'Preencheu todos os dados do perfil',
                'icon_name' => 'user-check',
                'icon_color' => '#3B82F6',
                'category' => 'onboarding',
                'rarity' => 'uncommon',
                'points_value' => 50,
                'criteria' => json_encode(['profile_completed' => true]),
                'is_active' => true,
                'is_secret' => false,
                'sort_order' => 2,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Documentos em Dia',
                'slug' => 'documents-uploaded',
                'description' => 'Enviou todos os documentos necessários',
                'icon_name' => 'file-check',
                'icon_color' => '#8B5CF6',
                'category' => 'onboarding',
                'rarity' => 'uncommon',
                'points_value' => 30,
                'criteria' => json_encode(['documents_complete' => true]),
                'is_active' => true,
                'is_secret' => false,
                'sort_order' => 3,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Health Badges
            [
                'name' => 'Check-up Completo',
                'slug' => 'health-checkup',
                'description' => 'Completou o questionário de saúde inicial',
                'icon_name' => 'heart',
                'icon_color' => '#EF4444',
                'category' => 'health',
                'rarity' => 'common',
                'points_value' => 40,
                'criteria' => json_encode(['health_questionnaire_completed' => true]),
                'is_active' => true,
                'is_secret' => false,
                'sort_order' => 10,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Vida Ativa',
                'slug' => 'active-lifestyle',
                'description' => 'Mantém um estilo de vida ativo',
                'icon_name' => 'running',
                'icon_color' => '#F59E0B',
                'category' => 'health',
                'rarity' => 'rare',
                'points_value' => 100,
                'criteria' => json_encode(['physical_activity_level' => ['active', 'very_active']]),
                'is_active' => true,
                'is_secret' => false,
                'sort_order' => 11,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Prevenção em Dia',
                'slug' => 'prevention-champion',
                'description' => 'Realizou todos os exames preventivos',
                'icon_name' => 'shield-check',
                'icon_color' => '#10B981',
                'category' => 'health',
                'rarity' => 'epic',
                'points_value' => 150,
                'criteria' => json_encode(['preventive_exams_complete' => true]),
                'is_active' => true,
                'is_secret' => false,
                'sort_order' => 12,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Engagement Badges
            [
                'name' => 'Usuário Frequente',
                'slug' => 'frequent-user',
                'description' => 'Acessa a plataforma regularmente',
                'icon_name' => 'calendar-check',
                'icon_color' => '#6366F1',
                'category' => 'engagement',
                'rarity' => 'common',
                'points_value' => 20,
                'criteria' => json_encode(['login_streak_days' => 7]),
                'is_active' => true,
                'is_secret' => false,
                'sort_order' => 20,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Maratonista',
                'slug' => 'streak-master',
                'description' => '30 dias consecutivos de acesso',
                'icon_name' => 'fire',
                'icon_color' => '#F97316',
                'category' => 'engagement',
                'rarity' => 'rare',
                'points_value' => 100,
                'criteria' => json_encode(['login_streak_days' => 30]),
                'is_active' => true,
                'is_secret' => false,
                'sort_order' => 21,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Embaixador',
                'slug' => 'ambassador',
                'description' => 'Convidou 5 pessoas para a plataforma',
                'icon_name' => 'users',
                'icon_color' => '#14B8A6',
                'category' => 'engagement',
                'rarity' => 'epic',
                'points_value' => 200,
                'criteria' => json_encode(['referrals' => 5]),
                'is_active' => true,
                'is_secret' => false,
                'sort_order' => 22,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Milestone Badges
            [
                'name' => 'Primeiro Mês',
                'slug' => 'first-month',
                'description' => 'Um mês usando a plataforma',
                'icon_name' => 'calendar',
                'icon_color' => '#9CA3AF',
                'category' => 'milestone',
                'rarity' => 'common',
                'points_value' => 50,
                'criteria' => json_encode(['days_since_registration' => 30]),
                'is_active' => true,
                'is_secret' => false,
                'sort_order' => 30,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Veterano',
                'slug' => 'veteran',
                'description' => 'Um ano de jornada saudável',
                'icon_name' => 'medal',
                'icon_color' => '#D97706',
                'category' => 'milestone',
                'rarity' => 'epic',
                'points_value' => 500,
                'criteria' => json_encode(['days_since_registration' => 365]),
                'is_active' => true,
                'is_secret' => false,
                'sort_order' => 31,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Special/Secret Badges
            [
                'name' => 'Early Adopter',
                'slug' => 'early-adopter',
                'description' => 'Um dos primeiros usuários da plataforma',
                'icon_name' => 'star',
                'icon_color' => '#FFD700',
                'category' => 'special',
                'rarity' => 'legendary',
                'points_value' => 1000,
                'criteria' => json_encode(['user_id' => ['<=', 100]]),
                'is_active' => true,
                'is_secret' => true,
                'sort_order' => 40,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'name' => 'Perfeccionista',
                'slug' => 'perfectionist',
                'description' => 'Completou tudo sem nenhum erro',
                'icon_name' => 'award',
                'icon_color' => '#DC2626',
                'category' => 'special',
                'rarity' => 'legendary',
                'points_value' => 300,
                'criteria' => json_encode(['perfect_onboarding' => true, 'zero_errors' => true]),
                'is_active' => true,
                'is_secret' => true,
                'sort_order' => 41,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('gamification_badges')->insert($badges);
    }
}