version: '3.8'

services:
  redis-master:
    image: redis:7.2-alpine
    container_name: redis-master
    hostname: redis-master
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/config/redis-master.conf:/usr/local/etc/redis/redis.conf:ro
      - redis_master_data:/data
    networks:
      - redis-ha
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  redis-slave-1:
    image: redis:7.2-alpine
    container_name: redis-slave-1
    hostname: redis-slave-1
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/config/redis-slave.conf:/usr/local/etc/redis/redis.conf:ro
      - redis_slave1_data:/data
    networks:
      - redis-ha
    ports:
      - "6380:6379"
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT=6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  redis-slave-2:
    image: redis:7.2-alpine
    container_name: redis-slave-2
    hostname: redis-slave-2
    restart: unless-stopped
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/config/redis-slave.conf:/usr/local/etc/redis/redis.conf:ro
      - redis_slave2_data:/data
    networks:
      - redis-ha
    ports:
      - "6381:6379"
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT=6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  redis-sentinel-1:
    image: redis:7.2-alpine
    container_name: redis-sentinel-1
    hostname: redis-sentinel-1
    restart: unless-stopped
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./redis/config/sentinel.conf:/usr/local/etc/redis/sentinel.conf:ro
      - sentinel1_data:/data
    networks:
      - redis-ha
    ports:
      - "26379:26379"
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    environment:
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER_TIMEOUT=10000
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "26379", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  redis-sentinel-2:
    image: redis:7.2-alpine
    container_name: redis-sentinel-2
    hostname: redis-sentinel-2
    restart: unless-stopped
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./redis/config/sentinel.conf:/usr/local/etc/redis/sentinel.conf:ro
      - sentinel2_data:/data
    networks:
      - redis-ha
    ports:
      - "26380:26379"
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    environment:
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER_TIMEOUT=10000
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "26379", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  redis-sentinel-3:
    image: redis:7.2-alpine
    container_name: redis-sentinel-3
    hostname: redis-sentinel-3
    restart: unless-stopped
    command: redis-sentinel /usr/local/etc/redis/sentinel.conf
    volumes:
      - ./redis/config/sentinel.conf:/usr/local/etc/redis/sentinel.conf:ro
      - sentinel3_data:/data
    networks:
      - redis-ha
    ports:
      - "26381:26379"
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    environment:
      - SENTINEL_QUORUM=2
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER_TIMEOUT=10000
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "26379", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 30s

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    restart: unless-stopped
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis-master:6379
      - REDIS_EXPORTER_INCL_SYSTEM_METRICS=true
    networks:
      - redis-ha
    depends_on:
      - redis-master

networks:
  redis-ha:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  redis_master_data:
    driver: local
  redis_slave1_data:
    driver: local
  redis_slave2_data:
    driver: local
  sentinel1_data:
    driver: local
  sentinel2_data:
    driver: local
  sentinel3_data:
    driver: local