# Version removed as it's obsolete in Docker Compose v2

services:
  mysql:
    image: mysql:8.0
    container_name: austa_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: ${DB_DATABASE:-onboarding_portal}
      MYSQL_USER: ${DB_USERNAME:-onboarding}
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_root_password
      - mysql_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$(cat /run/secrets/mysql_root_password)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis service updated for HA compatibility
  redis:
    image: redis:7-alpine
    container_name: austa_redis
    restart: unless-stopped
    command: redis-server --requirepass-file /run/secrets/redis_password
    secrets:
      - redis_password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--pass", "$$(cat /run/secrets/redis_password)", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    # Note: For High Availability, use docker-compose.redis-ha.yml instead

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: austa_backend
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      APP_ENV: ${APP_ENV:-local}
      APP_DEBUG: ${APP_DEBUG:-true}
      APP_URL: ${APP_URL:-http://localhost:8000}
      APP_KEY: base64:hhwp59ZT8Vvp+uXSm2AYPEsCk7VReajLWm9plEZQulQ=
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-onboarding_portal}
      DB_USERNAME: ${DB_USERNAME:-onboarding}
      DB_PASSWORD: ${DB_PASSWORD:-secure_password_123}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_CONNECTION: redis
    secrets:
      - app_key
      - db_password
      - redis_password
    volumes:
      - ./backend:/var/www/backend
    healthcheck:
      test: ["CMD", "sh", "-c", "cd /var/www/backend && php artisan health:check"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000/api
    container_name: austa_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000/api
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
      HOSTNAME: "0.0.0.0"
      PORT: 3000
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  nginx:
    image: nginx:1.25.3-alpine
    container_name: austa_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./backend/public:/var/www/backend/public
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 30s

  # Monitoring services
  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: austa_prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:10.2.0
    container_name: austa_grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD_FILE: /run/secrets/grafana_admin_password
      GF_USERS_ALLOW_SIGN_UP: false
      GF_SECURITY_DISABLE_GRAVATAR: true
      GF_ANALYTICS_REPORTING_ENABLED: false
      GF_ANALYTICS_CHECK_FOR_UPDATES: false
    secrets:
      - grafana_admin_password
    volumes:
      - grafana_data:/var/lib/grafana

  mysql_exporter:
    image: prom/mysqld-exporter:v0.15.0
    container_name: austa_mysql_exporter
    restart: unless-stopped
    command: 
      - "--mysqld.username=root"
      - "--mysqld.address=mysql:3306"
    environment:
      MYSQLD_EXPORTER_PASSWORD_FILE: /run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
    ports:
      - "9104:9104"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9104/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mysql_data:
    external: true
    name: onboardingportal_mysql_data
  redis_data:
    external: true
    name: onboardingportal_redis_data
  prometheus_data:
  grafana_data:

secrets:
  mysql_root_password:
    file: ./docker/secrets/mysql_root_password.txt
  mysql_password:
    file: ./docker/secrets/mysql_password.txt
  db_password:
    file: ./docker/secrets/db_password.txt
  redis_password:
    file: ./docker/secrets/redis_password.txt
  app_key:
    file: ./docker/secrets/app_key.txt
  grafana_admin_password:
    file: ./docker/secrets/grafana_admin_password.txt