# Development overrides for docker-compose
# Version removed as it's obsolete in Docker Compose v2

services:
  # Use development Dockerfile for frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: true
      NEXT_TELEMETRY_DISABLED: 1
      NEXT_PUBLIC_API_URL: http://localhost:8000/api
      WATCHPACK_POLLING: true
    command: npm run dev

  # Backend PHP development settings (extends backend service)
  backend:
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - XDEBUG_MODE=coverage,debug
      - XDEBUG_CONFIG=client_host=host.docker.internal
    volumes:
      - ./backend:/var/www/backend
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  # Development mail server
  mailhog:
    image: mailhog/mailhog:latest
    container_name: omni_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
  # PHPMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: omni_phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD:-root_password}
    depends_on:
      - mysql

  # Redis with no authentication for development
  redis:
    command: redis-server --protected-mode no --appendonly yes
    
  # Redis Commander for Redis management
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: omni_redis_commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
