version: '3.8'

# Docker Secrets Management Configuration for Omni Portal
# This file defines external secrets that must be created before running the application
# Run ./scripts/init-secrets.sh to initialize all required secrets

secrets:
  # Database secrets
  mysql_root_password:
    external: true
    name: austa_mysql_root_password
  
  mysql_password:
    external: true
    name: austa_mysql_password
  
  db_password:
    external: true
    name: austa_db_password
  
  # Redis secret
  redis_password:
    external: true
    name: austa_redis_password
  
  # Application secrets
  app_key:
    external: true
    name: austa_app_key
  
  # Monitoring secrets
  grafana_admin_password:
    external: true
    name: austa_grafana_admin_password
  
  # Additional production secrets
  jwt_secret:
    external: true
    name: austa_jwt_secret
  
  session_secret:
    external: true
    name: austa_session_secret
  
  # External service secrets (optional)
  openai_api_key:
    external: true
    name: austa_openai_api_key
  
  encryption_key:
    external: true
    name: austa_encryption_key
  
  # SMTP secrets (if email notifications are used)
  smtp_password:
    external: true
    name: austa_smtp_password

services:
  # MySQL Database with secrets
  mysql:
    image: mysql:8.0
    container_name: austa_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: ${DB_DATABASE:-onboarding_portal}
      MYSQL_USER: ${DB_USERNAME:-onboarding}
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    secrets:
      - mysql_root_password
      - mysql_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$(cat /run/secrets/mysql_root_password)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Redis with password from secrets
  redis:
    image: redis:7-alpine
    container_name: austa_redis
    restart: unless-stopped
    command: redis-server --requirepass $$(cat /run/secrets/redis_password)
    secrets:
      - redis_password
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "--pass", "$$(cat /run/secrets/redis_password)", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend application with secrets
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: austa_backend
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      APP_ENV: ${APP_ENV:-production}
      APP_DEBUG: ${APP_DEBUG:-false}
      APP_URL: ${APP_URL:-http://localhost:8000}
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_DATABASE: ${DB_DATABASE:-onboarding_portal}
      DB_USERNAME: ${DB_USERNAME:-onboarding}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      QUEUE_CONNECTION: redis
      # Secrets are read from files at runtime
      APP_KEY_FILE: /run/secrets/app_key
      DB_PASSWORD_FILE: /run/secrets/db_password
      REDIS_PASSWORD_FILE: /run/secrets/redis_password
    secrets:
      - app_key
      - db_password
      - redis_password
    volumes:
      - ./backend:/var/www/backend
    healthcheck:
      test: ["CMD", "sh", "-c", "cd /var/www/backend && php artisan health:check"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s

  # Frontend application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8000/api
    container_name: austa_frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:8000/api
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1
      HOSTNAME: "0.0.0.0"
      PORT: 3000
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Nginx reverse proxy
  nginx:
    image: nginx:1.25.3-alpine
    container_name: austa_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
      - "8443:443"
    volumes:
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./backend/public:/var/www/backend/public
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://127.0.0.1/health"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 30s

  # Monitoring services with secrets
  prometheus:
    image: prom/prometheus:v2.47.2
    container_name: austa_prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'

  grafana:
    image: grafana/grafana:10.2.0
    container_name: austa_grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_PASSWORD_FILE: /run/secrets/grafana_admin_password
      GF_USERS_ALLOW_SIGN_UP: false
      GF_SECURITY_DISABLE_GRAVATAR: true
      GF_ANALYTICS_REPORTING_ENABLED: false
      GF_ANALYTICS_CHECK_FOR_UPDATES: false
    secrets:
      - grafana_admin_password
    volumes:
      - grafana_data:/var/lib/grafana

  mysql_exporter:
    image: prom/mysqld-exporter:v0.15.0
    container_name: austa_mysql_exporter
    restart: unless-stopped
    command: 
      - "--mysqld.username=root"
      - "--mysqld.address=mysql:3306"
    environment:
      MYSQLD_EXPORTER_PASSWORD_FILE: /run/secrets/mysql_root_password
    secrets:
      - mysql_root_password
    ports:
      - "9104:9104"
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9104/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mysql_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local