# Prometheus Configuration for MySQL High Availability Monitoring

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # MySQL Exporter
  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
    scrape_interval: 5s
    metrics_path: /metrics

  # ProxySQL Exporter (if available)
  - job_name: 'proxysql'
    static_configs:
      - targets: ['proxysql:6032']
    scrape_interval: 15s
    metrics_path: /metrics

  # Orchestrator metrics
  - job_name: 'orchestrator'
    static_configs:
      - targets: ['orchestrator:3000']
    scrape_interval: 30s
    metrics_path: /api/status

  # Node exporter for system metrics (optional)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s

# Alerting
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Recording rules for MySQL HA metrics
rule_files:
  - "mysql_ha_rules.yml"