const mockApi = {
  post: jest.fn(),
  get: jest.fn(),
  put: jest.fn(),
  delete: jest.fn(),
  uploadFile: jest.fn(),
  setAuth: jest.fn(),
  clearAuth: jest.fn(),
  getGamificationProgress: jest.fn(),
  getGamificationStats: jest.fn(),
  getAchievements: jest.fn(),
  getLeaderboard: jest.fn(),
  getActivityFeed: jest.fn(),
  getDashboardSummary: jest.fn(),
  getGamificationLevels: jest.fn(),
  registerStep1: jest.fn(),
  registerStep2: jest.fn(),
  registerStep3: jest.fn(),
  getRegistrationProgress: jest.fn(),
  cancelRegistration: jest.fn(),
  getProfile: jest.fn(),
  updateProfile: jest.fn(),
  uploadProfilePhoto: jest.fn(),
  getLGPDPrivacySettings: jest.fn(),
  updateLGPDPrivacySettings: jest.fn(),
  getLGPDConsentHistory: jest.fn(),
  getLGPDDataProcessingActivities: jest.fn(),
  exportLGPDUserData: jest.fn(),
  exportLGPDUserDataPdf: jest.fn(),
  withdrawLGPDConsent: jest.fn(),
  deleteLGPDAccount: jest.fn(),
};

export default mockApi;