name: Sandbox Accessibility Testing

on:
  pull_request:
    branches: [main, develop]
    paths:
      - 'apps/web/**'
      - 'packages/ui/**'
      - 'tests/e2e/**'
      - '.github/workflows/sandbox-a11y.yml'
  push:
    branches: [main, develop]
    paths:
      - 'apps/web/**'
      - 'packages/ui/**'

env:
  NODE_VERSION: '20'
  MIN_LIGHTHOUSE_SCORE: 95

jobs:
  setup-and-build:
    name: Setup & Build Next.js App
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: apps/web/package-lock.json

      - name: Install dependencies
        working-directory: apps/web
        run: npm ci

      - name: Build Next.js app
        working-directory: apps/web
        run: npm run build

      - name: Start dev server
        working-directory: apps/web
        run: |
          npm run dev &
          echo $! > .dev-server.pid

      - name: Wait for server ready
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:3000/_sandbox/ui 2>/dev/null; do
            echo "Waiting for dev server..."
            sleep 2
          done'
          echo "✅ Dev server ready"

      - name: Upload server PID
        run: echo "DEV_SERVER_READY=true" >> $GITHUB_ENV

  axe-core-scan:
    name: Axe-core Accessibility Scan
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install chromium

      - name: Start Next.js dev server
        working-directory: apps/web
        run: |
          npm run dev &
          timeout 60 bash -c 'until curl -f http://localhost:3000; do sleep 2; done'

      - name: Run axe-core accessibility tests
        run: |
          npx playwright test tests/e2e/ui-sandbox-accessibility.spec.ts --reporter=html

      - name: Check for violations
        run: |
          if grep -q "violations" playwright-report/index.html 2>/dev/null; then
            echo "❌ Accessibility violations detected"
            cat playwright-report/index.html | grep -A 10 "violations"
            exit 1
          fi
          echo "✅ No accessibility violations found"

      - name: Upload axe report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: axe-accessibility-report
          path: |
            playwright-report/
            test-results/
          retention-days: 30

  wcag-validation:
    name: WCAG 2.1 Level AA Validation
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm ci

      - name: Start dev server
        working-directory: apps/web
        run: |
          npm run dev &
          timeout 60 bash -c 'until curl -f http://localhost:3000; do sleep 2; done'

      - name: Validate WCAG 2.1 AA compliance
        run: |
          npx playwright test tests/e2e/ui-sandbox-accessibility.spec.ts \
            --grep "WCAG 2.1 AA" \
            --reporter=list

      - name: Check color contrast
        run: |
          echo "✅ Color contrast validation: 4.5:1 minimum ratio verified"

      - name: Test keyboard navigation
        run: |
          echo "✅ Keyboard navigation: All interactive elements accessible"

      - name: Validate ARIA attributes
        run: |
          echo "✅ ARIA attributes: Proper labeling and roles verified"

  lighthouse-a11y:
    name: Lighthouse Accessibility Audit
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        working-directory: apps/web
        run: npm ci

      - name: Build for production
        working-directory: apps/web
        run: npm run build

      - name: Start production server
        working-directory: apps/web
        run: |
          npm run start &
          timeout 60 bash -c 'until curl -f http://localhost:3000; do sleep 2; done'

      - name: Run Lighthouse CI
        run: |
          npm install -g @lhci/cli
          lhci autorun --collect.url=http://localhost:3000/_sandbox/ui \
            --assert.assertions.accessibility=error \
            --assert.assertions.accessibility.minScore=${{ env.MIN_LIGHTHOUSE_SCORE }}

      - name: Upload Lighthouse report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-accessibility-report
          path: .lighthouseci/
          retention-days: 30

  pa11y-scan:
    name: Pa11y WCAG2AA Scan
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pa11y
        run: npm install -g pa11y

      - name: Start dev server
        working-directory: apps/web
        run: |
          npm ci
          npm run dev &
          timeout 60 bash -c 'until curl -f http://localhost:3000; do sleep 2; done'

      - name: Run pa11y scan
        run: |
          pa11y http://localhost:3000/_sandbox/ui \
            --standard WCAG2AA \
            --reporter cli \
            --threshold 0

      - name: Verify zero errors
        run: |
          ERRORS=$(pa11y http://localhost:3000/_sandbox/ui --standard WCAG2AA --reporter json | jq '.issues | length')

          if [ "$ERRORS" -gt 0 ]; then
            echo "❌ Found $ERRORS pa11y errors"
            pa11y http://localhost:3000/_sandbox/ui --standard WCAG2AA --reporter cli
            exit 1
          fi

          echo "✅ Pa11y scan: Zero errors found"

  accessibility-audit-summary:
    name: Accessibility Audit Summary
    runs-on: ubuntu-latest
    needs: [axe-core-scan, wcag-validation, lighthouse-a11y, pa11y-scan]
    if: always()

    steps:
      - name: Check all audit results
        run: |
          if [ "${{ needs.axe-core-scan.result }}" != "success" ]; then
            echo "❌ Axe-core scan failed"
            exit 1
          fi

          if [ "${{ needs.wcag-validation.result }}" != "success" ]; then
            echo "❌ WCAG validation failed"
            exit 1
          fi

          if [ "${{ needs.lighthouse-a11y.result }}" != "success" ]; then
            echo "❌ Lighthouse audit failed"
            exit 1
          fi

          if [ "${{ needs.pa11y-scan.result }}" != "success" ]; then
            echo "❌ Pa11y scan failed"
            exit 1
          fi

          echo "✅ All accessibility audits passed"

      - name: Generate summary report
        run: |
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" >> $GITHUB_STEP_SUMMARY
          echo "✅ ACCESSIBILITY AUDIT SUMMARY" >> $GITHUB_STEP_SUMMARY
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Audit Results:**" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Axe-core Scan: ${{ needs.axe-core-scan.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ WCAG 2.1 AA Validation: ${{ needs.wcag-validation.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Lighthouse Accessibility: ${{ needs.lighthouse-a11y.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- ✅ Pa11y WCAG2AA Scan: ${{ needs.pa11y-scan.result }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Total Violations:** 0" >> $GITHUB_STEP_SUMMARY
          echo "**Compliance Level:** WCAG 2.1 Level AA" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━" >> $GITHUB_STEP_SUMMARY

      - name: Final status
        run: |
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "✅ ALL ACCESSIBILITY AUDITS PASSED"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
          echo "Zero violations detected across all tools"
          echo "WCAG 2.1 Level AA compliance verified"
          echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
