name: UI Purity Check (ADR-003)

on:
  pull_request:
    paths:
      - 'packages/ui/**'
  push:
    branches: [main, develop]

jobs:
  check-purity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run UI purity check
        run: |
          chmod +x scripts/verify-ui-purity.sh
          bash scripts/verify-ui-purity.sh
